language: python

python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

os:
  - windows
  - linux
  - osx


# matrix:
#   include:
#     - os: linux
#       sudo: required
#       dist: xenial
#
#     - os: linux
#       sudo: required
#       dist: xenial
#
#     - os: linux
#       sudo: required
#       dist: xenial
#
#     - os: linux
#       sudo: required
#       dist: xenial
#
#     - os: osx
#       osx_image: xcode10
#       language: generic
#       env: PYTHON=36


install:
  - pip install -e .

script:
  - python --version
  - pytest

after_success:
  - coveralls
  - pip uninstall -y tflit

after_failure:
  - pip uninstall -y tflit
