language: python

notifications:
  email: false

dist: bionic

cache:
  apt: True
  directories:
    - $HOME/Library/Caches/pip

matrix:
  include:
    - python: 3.5
      os: linux
    - python: 3.6
      os: linux
    - python: 3.7
      os: linux
    # - python: 3.8
    #   os: linux

    - &linuxarm
      os: linux
      dist: trusty
      arch: arm64
      python: 3.5
    - <<: *linuxarm
      python: 3.6
    - <<: *linuxarm
      python: 3.7
    # - <<: *linuxarm
    #   python: 3.8

    # - name: "Python: 3.5"
    #   os: osx
    #   language: shell
    #   python: 3.5
    - &osx
      name: "Python: 3.5"
      os: osx
      osx_image: xcode11.3
      language: shell
      env: PYVERSION=3.5
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda info -a
        - echo $PYVERSION
        - conda create -q -n venv python=$PYVERSION
        - source activate venv
    - <<: *osx
      name: "Python: 3.6"
      env: PYVERSION=3.6
    - <<: *osx
      name: "Python: 3.7"
      env: PYVERSION=3.7

    - name: "Python 3.5.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH


install:
  - |
    for f in $(which -a python); do                                                                                                                                                                                                                    [17:22]
      ls -lah $f*
    done;
  # - '[[ "$(python3 -V)" =~ "Python 3" ]] && python3 -V && which python3 && alias python=python3 || true'
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade -e .[tests]

script:
  - python -m pytest --cov=tflit --cov-report term-missing

after_success:
  - python -m pip uninstall -y tflit

after_failure:
  - python -m pip uninstall -y tflit
