language: python

notifications:
  email: false

dist: trusty

cache:
  apt: True
  directories:
    - $HOME/Library/Caches/pip

matrix:
  include:
    - python: 3.5
      os: linux
    - python: 3.6
      os: linux
    - python: 3.7
      os: linux
    - python: 3.8
      os: linux

    - python: 3.5
      os: linux
      arch: arm64
    - python: 3.6
      os: linux
      arch: arm64
    - python: 3.7
      os: linux
      arch: arm64
    # - python: 3.8
    #   os: linux
    #   arch: arm64

    # - name: "Python: 3.5"
    #   os: osx
    #   language: shell
    #   python: 3.5
    - name: "Python: 3.6"
      os: osx
      osx_image: xcode9.4  # 3.6.5
      language: shell
      python: 3.6
    - name: "Python: 3.7"
      os: osx
      osx_image: xcode10.2  # 3.7.3
      language: shell
      python: 3.7

    - name: "Python 3.5.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH


install:
  - '[[ "$(python3 -V)" =~ "Python 3" ]] && alias python=python3'
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade -e .[tests]

script:
  - python -m pytest --cov=tflit --cov-report term-missing

after_success:
  - python -m pip uninstall -y tflit

after_failure:
  - python -m pip uninstall -y tflit
